#include <stdio.h>
#include <stdlib.h>

int main()
{
    //宣告整數a並給予值 
    int a=5;
    printf("the number a is %3d\n",a);
    
    //宣告長整數b並給予值 
    long int b=80000;
    printf("the number b is %ld\n",b);
    
    //宣告浮點數c並給予值 
    float c=123.45;
    printf("the number c is %f\n",c);
    
    //宣告字元d並給予值 
    char d='d';
    printf("the char d is %c\n",d);
    
    system("PAUSE");
    return 0;   
}
